/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.netology.pyas.missedcalls;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.stream.Stream;

class ContactGroupTest {

    @ParameterizedTest
    @MethodSource("getTitleTestDataProvider")
    public void getTitle(ContactGroup group, String expected) {
        String actual = group.getTitle();
        assertEquals(expected, actual);
    }

    private static Stream<Arguments> getTitleTestDataProvider() {
        return Stream.of(
            Arguments.of(ContactGroup.FAMILY, "Семья"),
            Arguments.of(ContactGroup.FRIENDS, "Друзья"),
            Arguments.of(ContactGroup.WORK, "Работа")
        );
    }

}
